# This is a temporary dummy config to stop CircleCI from building this branch with automatic v1.0 configuration for PHP

version: 2
jobs:
  build:
    docker:
      - image: docker:edge-dind
    steps:
      - run: apk add --no-cache git openssh-client bash
      - checkout
      - setup_remote_docker
      - run: echo 'Hello World'
